### ISSUE TITLE
Missing Libconfig.pm

### ISSUE THREAD

**Issue by shadowlmd** [yrutschle/conf2struct#4] opened 2019-06-28 11:44 UTC
When I'm trying to run conf2struct, it tells me that Conf/Libconfig.pm is not found. I am not sure where I can find this because Ubuntu 16.04 doesn't seem to provide it:
```
$ apt-file --regexp search '/[Ll]ibconfig\.pm$'
$ lsb_release -d
Description:    Ubuntu 16.04.6 LTS
```

**Comment by yrutschle** [comment] 2019-06-29 16:14
You should be able to install it from CPAN:
```
cpan Conf::Libconfig
```

I'll add an install note, this should be documented...

**Comment by shadowlmd** [comment] 2019-06-30 10:05
Wouldn't it be better to put this lib in this repo to avoid dependency issues? I need conf2struct only because it is required to build sslh now, and it starts to be very complicated to build it automatically.

**Comment by yrutschle** [comment] 2019-06-30 14:16
Fair enough. I'm thinking I can add a Makefile target to install the dependencies (`make get_deps` or something) which would do that. I was planning to do something similar in sslh to retrieve the correct version of `conf2struct` as well.

**Comment by shadowlmd** [comment] 2019-07-01 13:17
Sounds good if it will not require root to install something.

**Comment by yrutschle** [comment] 2019-07-03 20:24
Unlikely -- you'll still need to install a variety of headers e.g. for libconfig, and I know no distribution that manages header packages without being root.

**Comment by candrews** [comment] 2019-07-06 00:17
If you do this, please make sure to not do it by default or at least have a way to turn that off. Linux distributions do not like such bundling. :)

**Comment by shadowlmd** [comment] 2019-07-06 09:18
> Unlikely -- you'll still need to install a variety of headers e.g. for libconfig, and I know no distribution that manages header packages without being root.

Headers and other stuff that can be installed with system package manager is not a problem. What I don't want is cpan messing up with my system. I couldn't force it install Libconfig.pm under local user.

**Comment by yrutschle** [comment] 2019-07-08 20:27
@candrews :
> If you do this, please make sure to not do it by default

Erm, if I do what? :)

@shadowlmd:
> I don't want is cpan messing up with my system

The problem is that Libconfig.pm does not come alone: I think it's juste a thin Perl wrapper on a C wrapper that actually uses the C library; this means installing Libconfig.pm involves compiling stuff.

FWIW, I've never seen CPAN messing up a system.

**Comment by shadowlmd** [comment] 2019-07-08 20:36
Compiling stuff is fine but I prefer to have everything compiled under local account, not system-wide. And cpan doesn't allow me to do that. :(

**Comment by candrews** [comment] 2019-07-09 03:16
> @candrews :
> 
> > If you do this, please make sure to not do it by default
> 
> Erm, if I do what? :)

It just makes it hard for Linux distros. They'll have to patch the build process to not use / remove those bundled dependencies. And I'm guessing that you'd like to have this work published in distros for ease of use by users.

For information on why bundling dependencies is so bad, and why it's against the policy of every Linux distro, see:
https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/bundled-libs.html
https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
https://flameeyes.blog/2009/01/02/bundling-libraries-for-despair-and-insecurity/

So I guess the "or what" is it'll be less likely that your work will be included in distros, less likely that it'll be used by users, and more likely to end up with security and other problems as a result of the bundling.

BTW, I'm a Gentoo Linux developer. I maintain [sslh](https://packages.gentoo.org/packages/net-misc/sslh) in Gentoo and recently added [conf2struct](https://packages.gentoo.org/packages/dev-util/conf2struct).

**Comment by yrutschle** [comment] 2019-07-09 19:26
@candrews: I just meant to clarify the value of 'this', which was ambiguous in the stream of conversation. Thanks for the link, I agree for the most part (I hated to bundle argtable3, and will happily drop it if it gets packaged for Debian).

@shadowlmd : I suppose you can use CPAN in a LXC, but that is certainly more complicated. I'll see if it's easy to request it being packaged for Debian, as that's the cleanest way (I too prefer to install distro packages before cpan)

**Comment by shadowlmd** [comment] 2019-07-10 08:24
@yrutschle, I figured how to work this around. I've installed liblocal-lib-perl and then ran cpan -I Conf::Libconfig, it installed everything for local user and added required environment variables to .bashrc so perl could use it. Now I have another issue building sslh:
```
Use of uninitialized value $c_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 660.
Use of uninitialized value $c_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 660.
Use of uninitialized value $c_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 660.
Use of uninitialized value $c_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 660.
Use of uninitialized value $c_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 660.
Use of uninitialized value $c_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 660.
Use of uninitialized value $c_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 660.
Use of uninitialized value $c_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 660.
Use of uninitialized value $arg_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 1122.
Use of uninitialized value $arg_type in string eq at /home/sslh/bin/conf2struct line 1128.
Use of uninitialized value $arg_type in pattern match (m//) at /home/sslh/bin/conf2struct line 1129.
Use of uninitialized value $arg_type in string eq at /home/sslh/bin/conf2struct line 1130.
Use of uninitialized value $arg_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 1134.
Use of uninitialized value $arg_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 1122.
Use of uninitialized value $arg_type in string eq at /home/sslh/bin/conf2struct line 1128.
Use of uninitialized value $arg_type in pattern match (m//) at /home/sslh/bin/conf2struct line 1129.
Use of uninitialized value $arg_type in string eq at /home/sslh/bin/conf2struct line 1130.
Use of uninitialized value $arg_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 1134.                                                                                                   
Use of uninitialized value $arg_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 1122.
Use of uninitialized value $arg_type in string eq at /home/sslh/bin/conf2struct line 1128.
Use of uninitialized value $arg_type in pattern match (m//) at /home/sslh/bin/conf2struct line 1129.
Use of uninitialized value $arg_type in string eq at /home/sslh/bin/conf2struct line 1130.
Use of uninitialized value $arg_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 1134.
Use of uninitialized value $arg_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 1122.
Use of uninitialized value $arg_type in string eq at /home/sslh/bin/conf2struct line 1128.
Use of uninitialized value $arg_type in pattern match (m//) at /home/sslh/bin/conf2struct line 1129.
Use of uninitialized value $arg_type in string eq at /home/sslh/bin/conf2struct line 1130.
Use of uninitialized value $arg_type in concatenation (.) or string at /home/sslh/bin/conf2struct line 1134.
Use of uninitialized value $sizeof in concatenation (.) or string at /home/sslh/bin/conf2struct line 826.
Use of uninitialized value $sizeof in concatenation (.) or string at /home/sslh/bin/conf2struct line 826.
Use of uninitialized value $sizeof in concatenation (.) or string at /home/sslh/bin/conf2struct line 826.
Use of uninitialized value $sizeof in concatenation (.) or string at /home/sslh/bin/conf2struct line 826.
Use of uninitialized value $sizeof in concatenation (.) or string at /home/sslh/bin/conf2struct line 826.
Use of uninitialized value $sizeof in concatenation (.) or string at /home/sslh/bin/conf2struct line 826.
Use of uninitialized value $sizeof in concatenation (.) or string at /home/sslh/bin/conf2struct line 826.
Use of uninitialized value $sizeof in concatenation (.) or string at /home/sslh/bin/conf2struct line 826.
Use of uninitialized value $fmt in concatenation (.) or string at /home/sslh/bin/conf2struct line 1029.
Use of uninitialized value $fmt in concatenation (.) or string at /home/sslh/bin/conf2struct line 1029.
Use of uninitialized value $fmt in concatenation (.) or string at /home/sslh/bin/conf2struct line 1029.
Use of uninitialized value $fmt in concatenation (.) or string at /home/sslh/bin/conf2struct line 1029.
Use of uninitialized value $fmt in concatenation (.) or string at /home/sslh/bin/conf2struct line 1029.
Use of uninitialized value $fmt in concatenation (.) or string at /home/sslh/bin/conf2struct line 1029.
Use of uninitialized value $fmt in concatenation (.) or string at /home/sslh/bin/conf2struct line 1029.
Use of uninitialized value $fmt in concatenation (.) or string at /home/sslh/bin/conf2struct line 1029.
Unknown type boolean
Makefile:76: recipe for target 'sslh-conf.c' failed
```
This is Ubuntu 16.04 with system perl 5.22.1, `/home/sslh/bin/conf2struct` is a symlink to `/home/sslh/git/conf2struct/conf2struct`.

**Comment by candrews** [comment] 2019-07-10 11:49
> Unknown type boolean
> Makefile:76: recipe for target 'sslh-conf.c' failed

See https://github.com/yrutschle/sslh/issues/230

**Comment by yrutschle** [comment] 2019-08-16 08:16
(I've documented your solution to install the Perl module as non-root user in c2s' INSTALL.md, so I'm closing this now).

**Closed as completed by yrutschle** 2019-08-16 08:16 UTC
